# docker-compose.yml
version: "3.8"
services:
  nginx:
    build: ./nginx
    ports:
      - "443:443"
    volumes:
        - "wp:/wordpress"
    env_file:
      - .env
    networks:
      - wordpress-nginx
    restart: always
    depends_on:
      - wordpress

  mariadb:
    build: ./mariadb
    ports:
        - '3306:3306'
    volumes:
        - ./db-data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - wordpress-mariadb
    restart: always
  
  wordpress:
    build: ./wordpress
    ports:
        - '9000:9000'
    volumes:
        - "wp:/wordpress"
    env_file:
      - .env
    links:
        - mariadb
    networks:
      - wordpress-mariadb
      - wordpress-nginx
    depends_on:
      - mariadb
    restart: always

networks:
  wordpress-nginx:
  wordpress-mariadb:

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: /home/jyurrita/Desktop/voulmesIncepion/db
      o: bind
  wp:
    driver: local
    driver_opts:
      type: none
      device: /home/jyurrita/Desktop/voulmesIncepion/wordpress
      o: bind